Add some more experimental coroutine builders for ServiceCall
taymyr/lagom-extensions pull request #15
Opened 2020-10-13 22:10 UTC by gnuzzz

2020-10-13 22:13 UTC, gnuzzz commented
@ihostage need review

2020-10-15 17:46 UTC, ihostage requested changes

2020-10-15 17:46 UTC, ihostage commented on buildSrc/src/main/kotlin/Variables.kt
> +val Project.lagomPac4jVersion get() = this.properties["lagomPac4jVersion"] as String? ?: Versions.lagomPac4j
This changes non needed

2020-10-15 17:46 UTC, ihostage commented on java/src/test/kotlin/org/taymyr/lagom/javadsl/api/ServiceCallBuildersTest.kt
> +    @Test
Please, to add @DisplayName for all tests.

2020-10-15 17:46 UTC, ihostage commented on java/src/test/kotlin/org/taymyr/lagom/javadsl/api/ServiceCallBuildersTest.kt
> +                    .invoke().await()
Maybe create extension function `await() = invoke().await()` for `ServiceCall`?

2020-10-15 18:21 UTC, ihostage approved these changes
LGTM

2020-10-15 18:26 UTC, merged